MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (1, '사과', 1500);
MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (2, '바나나', 800);
MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (3, '오렌지', 2000);
MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (4, '포도', 3500);
MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (5, '딸기', 4000);
MERGE INTO PRODUCT (ID, NAME, PRICE) VALUES (6, '불량상품', 0);